# Generated by Django 4.2.4 on 2023-08-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ombriere_typeborne_bornerecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bornerecharge',
            name='type_borne',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Ombriere',
        ),
        migrations.DeleteModel(
            name='BorneRecharge',
        ),
        migrations.DeleteModel(
            name='TypeBorne',
        ),
        migrations.AddField(
            model_name='range',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section'),
        ),
        migrations.AddField(
            model_name='borne',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.range'),
        ),
    ]
