# Generated by Django 4.2.4 on 2023-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_borne_range_section_remove_bornerecharge_type_borne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borne',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='borne',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload/'),
        ),
        migrations.AddField(
            model_name='borne',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
